In [1]:
import numpy as np
import pandas as pd

In [5]:
import pandas as pd

students = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4],
    "Name": ["Niraj", "Rahul", "Aman", "Priya"],
    "Department": ["CSE", "ECE", "ME", "CE"]
})

marks = pd.DataFrame({
    "Student_ID": [1, 2, 3, 5],
    "Marks": [85, 78, 92, 88]
    

})

print(students)
print(marks)

   Student_ID   Name Department
0           1  Niraj        CSE
1           2  Rahul        ECE
2           3   Aman         ME
3           4  Priya         CE
   Student_ID  Marks
0           1     85
1           2     78
2           3     92
3           5     88

In [9]:
pd.merge(students, marks, on='Student_ID',how = 'outer')

   Student_ID   Name Department  Marks
0           1  Niraj        CSE   85.0
1           2  Rahul        ECE   78.0
2           3   Aman         ME   92.0
3           4  Priya         CE    NaN
4           5    NaN        NaN   88.0

In [10]:
pd.merge(students, marks, on='Student_ID',how = 'left')

   Student_ID   Name Department  Marks
0           1  Niraj        CSE   85.0
1           2  Rahul        ECE   78.0
2           3   Aman         ME   92.0
3           4  Priya         CE    NaN

In [14]:
#Concatination of dataframes

import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Niraj", "Rahul", "Aman"],
    "Marks": [85, 78, 92]
})

df2 = pd.DataFrame({
    "Name": ["Priya", "Neha", "Riya"],
    "Marks": [88, 90, 95]
})

In [15]:
df1

    Name  Marks
0  Niraj     85
1  Rahul     78
2   Aman     92

In [16]:
df2

    Name  Marks
0  Priya     88
1   Neha     90
2   Riya     95

In [19]:
pd.concat([df1, df2])

    Name  Marks
0  Niraj     85
1  Rahul     78
2   Aman     92
0  Priya     88
1   Neha     90
2   Riya     95

In [21]:
pd.concat([df1, df2], axis=1)

    Name  Marks   Name  Marks
0  Niraj     85  Priya     88
1  Rahul     78   Neha     90
2   Aman     92   Riya     95

In [22]:
#joining of dataframes

In [23]:
df1 = pd.DataFrame({
    "Name": ["Niraj", "Rahul", "Aman"],
    "Marks": [85, 78, 92]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "City": ["Ranchi", "Patna", "Delhi"],
    "Age": [21, 22, 20]
}, index=[1, 2, 3])

In [24]:
df1

    Name  Marks
1  Niraj     85
2  Rahul     78
3   Aman     92

In [25]:
df1.join(df2)

    Name  Marks    City  Age
1  Niraj     85  Ranchi   21
2  Rahul     78   Patna   22
3   Aman     92   Delhi   20

In [ ]:
df1.join(df2)