In [13]:
import numpy as np
import pandas as pd

In [14]:

data = {
    "Name": ["Rahul", "Priya", "Aman", "Neha"],
    "Age": [20, 21, np.nan, 22],
    "Marks": [85, np.nan, 90, 88]
}

df = pd.DataFrame(data)

print(df)

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  21.0    NaN
2   Aman   NaN   90.0
3   Neha  22.0   88.0

In [15]:
df.isna()

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False

In [16]:
df.isna().sum()

Name     0
Age      1
Marks    1
dtype: int64

In [17]:
df.isna().any()

Name     False
Age       True
Marks     True
dtype: bool

In [18]:
# Remove Missing Data :- esko remove krne ke liye rows ke basis pr depend krta hai


df

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  21.0    NaN
2   Aman   NaN   90.0
3   Neha  22.0   88.0

In [19]:
df.dropna() #dropna krne se value ko remove kr sakte hia esko use krte hi dara data hi remove ho jayega

    Name   Age  Marks
0  Rahul  20.0   85.0
3   Neha  22.0   88.0

In [20]:
df.dropna(thresh=1)  #thresh ka matlab yeh hai ki mere data me 3 null value rhna chahiye

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  21.0    NaN
2   Aman   NaN   90.0
3   Neha  22.0   88.0

In [21]:
# Filling missing data  : - eska matlab yah hia ki missing value ko fill kr sakte hai 

df.fillna(0)

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  21.0    0.0
2   Aman   0.0   90.0
3   Neha  22.0   88.0

In [22]:
values = {'Age':45,'Marks':100}
df.fillna(value=values)

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  21.0  100.0
2   Aman  45.0   90.0
3   Neha  22.0   88.0

In [23]:
#agar hum kise ek particuller value ke under ki value ko fill krne chahiye toh 

df.fillna(df.mean())

TypeError: Cannot perform reduction 'mean' with string dtype