In [1]:
import numpy as np
import pandas as pd

In [5]:
# create a series 
labels = ['a', 'b', 'c', 'd']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10, 2:20 ,3:30}

In [6]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(my_list, index=labels[:len(my_list)])

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [18]:
# ///////////// Creating a dataFrame //////////

import pandas as pd

data = {
    "Name": ["Rahul", "Rohan", "Priya"],
    "Age": [20, 21, 19],
    "Marks": [90, 85, 95],
    "City": ["Delhi", "Mumbai", "Patna"]
}
pd.DataFrame(data)   #eska use kr ke humlog data frame create kr sakte hai

    Name  Age  Marks    City
0  Rahul   20     90   Delhi
1  Rohan   21     85  Mumbai
2  Priya   19     95   Patna

In [19]:
import numpy as np
import pandas as pd

data = {
    "Roll_No": [101, 102, 103, 104],
    "Name": ["Rahul", "Priya", "Aman", "Neha"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 92, 78, 88]
}
pd.DataFrame(data)
columns = ["name","age","City", "Salary"]
df2 = pd.DataFrame(data,columns = columns)
df2

Empty DataFrame
Columns: [name, age, City, Salary]
Index: []

In [20]:
# Selection And Indexing of columns

import pandas as pd

data = {
    "Roll_No": [101, 102, 103, 104],
    "Name": ["Rahul", "Priya", "Aman", "Neha"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 92, 78, 88]
}

df = pd.DataFrame(data)

print(df)

   Roll_No   Name  Age  Marks
0      101  Rahul   20     85
1      102  Priya   21     92
2      103   Aman   19     78
3      104   Neha   22     88

In [21]:
df

   Roll_No   Name  Age  Marks
0      101  Rahul   20     85
1      102  Priya   21     92
2      103   Aman   19     78
3      104   Neha   22     88

In [22]:
df[["Name","Marks"]]

    Name  Marks
0  Rahul     85
1  Priya     92
2   Aman     78
3   Neha     88

In [23]:
df[["Name"]]

    Name
0  Rahul
1  Priya
2   Aman
3   Neha

In [24]:
df["Designation"] = ["Doctor","Eng","Doctor","Eng"]   #esse ek new list ban jati hai or agar hum list create krte time jitna column hai utna hi naam likhna hoga or agar galti se 3 list banaye ya fir 5 list banaye toh error aa jayega ese liye jitna lish hai utna hi list bana ahoga 

df

   Roll_No   Name  Age  Marks Designation
0      101  Rahul   20     85      Doctor
1      102  Priya   21     92         Eng
2      103   Aman   19     78      Doctor
3      104   Neha   22     88         Eng

In [ ]:
# esse humlo column ko delete kr sakte hai 
df.drop("Designation", axis=1,inplace=True ) #implace ka matlab yah hai ki jab humlog kisi bhi chis ka drop krte hai toh usko inplace laga kr kisi bhi area ko remove kr sakte hai 

# Display DataFrame
print(df)

   Roll_No   Name  Age  Marks
0      101  Rahul   20     85
1      102  Priya   21     92
2      103   Aman   19     78
3      104   Neha   22     88

In [28]:
df.drop(0,axis = 0)  #esse humlog row ko delete kr sakte hai

   Roll_No   Name  Age  Marks
1      102  Priya   21     92
2      103   Aman   19     78
3      104   Neha   22     88

In [50]:
#Selecting Row

import pandas as pd

data = {
    "Roll_No": [101, 102, 103, 104],
    "Name": ["Rahul", "Priya", "Aman", "Neha"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 92, 78, 88]
}

df = pd.DataFrame(data)

print(df)

   Roll_No   Name  Age  Marks
0      101  Rahul   20     85
1      102  Priya   21     92
2      103   Aman   19     78
3      104   Neha   22     88

In [51]:
df.loc[[0,1,2]]

   Roll_No   Name  Age  Marks
0      101  Rahul   20     85
1      102  Priya   21     92
2      103   Aman   19     78

In [52]:
df.iloc[3]

Roll_No     104
Name       Neha
Age          22
Marks        88
Name: 3, dtype: object

In [53]:
df.loc[[2,3]][["Age","Name"]]

   Age  Name
2   19  Aman
3   22  Neha

In [54]:
# conditional Selection

# i only want to see those people whose age is above 30

df[df["Age"]>20]

   Roll_No   Name  Age  Marks
1      102  Priya   21     92
3      104   Neha   22     88

In [58]:
# i only want people whose age is abhove 30 and their cirt must be pari

df[(df["Age"] > 21) & (df["Marks"]=='21')]

Empty DataFrame
Columns: [Roll_No, Name, Age, Marks]
Index: []