In [1]:
import numpy as np
import pandas as pd

In [5]:
# create a series 
labels = ['a', 'b', 'c', 'd']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10, 2:20 ,3:30}

In [6]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(my_list, index=labels[:len(my_list)])

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [2]:
# ///////////// Creating a dataFrame //////////

import pandas as pd

data = {
    "Name": ["Rahul", "Rohan", "Priya"],
    "Age": [20, 21, 19],
    "Marks": [90, 85, 95],
    "City": ["Delhi", "Mumbai", "Patna"]
}
pd.DataFrame(data)   #eska use kr ke humlog data frame create kr sakte hai

    Name  Age  Marks    City
0  Rahul   20     90   Delhi
1  Rohan   21     85  Mumbai
2  Priya   19     95   Patna

In [6]:
import numpy as np
import pandas as pd

data = {
    "Roll_No": [101, 102, 103, 104],
    "Name": ["Rahul", "Priya", "Aman", "Neha"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 92, 78, 88]
}
pd.DataFrame(data)
columns = ["name","age","City", "Salary"]
df2 = pd.DataFrame(data,columns = columns)
df2

Empty DataFrame
Columns: [name, age, City, Salary]
Index: []

In [8]:
# Selection And Indexing of columns

import pandas as pd

data = {
    "Roll_No": [101, 102, 103, 104],
    "Name": ["Rahul", "Priya", "Aman", "Neha"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 92, 78, 88]
}

df = pd.DataFrame(data)

print(df)

   Roll_No   Name  Age  Marks
0      101  Rahul   20     85
1      102  Priya   21     92
2      103   Aman   19     78
3      104   Neha   22     88